### ISSUE TITLE
Running out of the map

### ISSUE THREAD

**Issue by anthony-lam** [jli37/Gungeon#1]
Why does the character just leave the map!
PLz help

**Comment by anthony-lam** [comment]
Is this a dodging game?

**Comment by Areo-0** [comment]
yes, we've built the game based on our current code

**Comment by anthony-lam** [comment]
i cant find my character what do

**Comment by Areo-0** [comment]
refresh the page

**Comment by jli452** [comment]
Thanks for your input @anthony-lam . I have taken it into consideration.

**Comment by JohnsonLi** [comment]
STILL AN ISSUE

**Comment by jli452** [comment]
What is the issue
