### ISSUE TITLE
Objective?

### ISSUE THREAD

**Issue by anthony-lam** [jli37/Gungeon#2]
What is the objective of this game? What am I suppose to do?

**Comment by anthony-lam** [comment]
Pretty fun tho

**Comment by JohnsonLi** [comment]
sorry @anthony-lam  you're wrong

**Comment by jli452** [comment]
Thanks for your input @anthony-lam . I have taken it into consideration.

**Comment by JohnsonLi** [comment]
REOPEN

**Comment by jli452** [comment]
Is there an issue?

**Comment by JohnsonLi** [comment]
your pfp
